Numpy Installation


In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


Making Arrays in Numpy

In [4]:
import numpy as np

arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [8]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [10]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

2D array

In [13]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


Numpy Vectorized Operation

In [27]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#operations
addition = arr1 + arr2
substraction = arr2 - arr1
multiplication = arr1*arr2
division = arr1/arr2

print(addition)
print(substraction)
print(multiplication)
print(division)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [29]:
#Universal Functions

arr1=(1,2,3,4,5)

print(np.sqrt(arr1))
print(np.sin(arr1))
print(np.exp(arr1))
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


Array slicing and Indexing

In [32]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
arr[0][3]

np.int64(4)

In [40]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [47]:
print(arr)
arr[0:3,1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

Modify array elements

In [48]:
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [49]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


Some practical use of arrays

In [54]:
# Stastical concept -------- NORMALIZATION
# It means mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculation mean and SD
mean = np.mean(data)
std_dev = np.std(data)

# Normalization = (data-mean)/sd

normalization = (data-mean)/std_dev

print("Normalized data =", normalization)

Normalized data = [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Calculating Mean, median, sd, variance

In [59]:
arr= np.array([1,2,3,4,5])

mean = np.mean(arr)
median = np.median(arr)
sd = np.std(arr)
variance = np.var(arr)

print(mean)
print(median)
print(sd)
print(variance)

3.0
3.0
1.4142135623730951
2.0


In [61]:
# Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5)&(data<=8)]

array([6, 7, 8])