### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np

arr1 = np.random.randint(1, 21, size=(5, 5))
arr1[:, 2] = 1

print("Array after replacing 3rd column with 1:")
print(arr1)

Array after replacing 3rd column with 1:
[[ 5 16  1 16 14]
 [ 7  3  1  2 17]
 [18 16  1  9  3]
 [11 13  1  4 17]
 [18  2  1 19  3]]


In [2]:
arr2 = np.arange(1, 17).reshape(4, 4)

np.fill_diagonal(arr2, 0)

print("\nArray after replacing diagonal elements with 0:")
print(arr2)


Array after replacing diagonal elements with 0:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
